"""
# WARNING: This file is auto-generated. Do not edit it directly.
# Generated by template manager
# Edit the template in src/templates/model.j2 or model_definitions/contacts.json instead
"""

from uuid import uuid4
from sqlalchemy import Column, String, Float, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import UUID
from src.models.base import Base

class Contacts(Base):
    """Contacts model representing connections to users"""
    __tablename__ = "contacts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    name = Column(String(100), nullable=False)
    avatar = Column(String(255))
    apps = Column(JSON)
    ai_engagement_score = Column(Float)
    preferred_contact_method = Column(String(50))
    last_interaction = Column(DateTime(timezone=True))
    location = Column(String(100))
    mood = Column(String(50))
    achievements = Column(JSON)
    communication_preferences = Column(JSON)
    relationships = Column(JSON)
    stats = Column(JSON)
    tags = Column(JSON)
    custom_fields = Column(JSON)
    availability = Column(JSON)
    summary = Column(Text)
    interests = Column(JSON)
    notes = Column(Text)
    relationship_summary = Column(Text)
    communication_style = Column(String(50))
    birthday = Column(String(20))
    user_id = Column(UUID(as_uuid=True), ForeignKey('users.id', ondelete="CASCADE"))

    # Relationship
    user = relationship("Users", back_populates="contacts")

    def __repr__(self):
        return f"<Contact(id={self.id}, name={self.name})>"
    
    
